const icons =
{
    class: require('../../../images/Class.png'),
    weapons: require('../../../images/Weapons.png'),
    armor: require('../../../images/Armor.png'),
    talismans: require('../../../images/Talismans.png'),
    spells: require('../../../images/Spells.png'),
    stats: require('../../../images/Stats.png'),
    empty: require('../../../images/Empty.png'),
    empty_slot: require('../../../images/Empty_slot.png'),
    right_hand: require('../../../images/Right_hand.png'),
    left_hand: require('../../../images/Left_hand.png'),
    saves: require('../../../images/saves.png'),
    share: require('../../../images/share.png'),
    home: require('../../../images/home_icon.png'),
    ranking: require('../../../images/ranking.png'),
    map: require('../../../images/map.jpg'),
    logout: require('../../../images/logout.png'),
    helmet: require('../../../images/Helmet.png'),
    chestplate: require('../../../images/Armor.png'),
    gauntlets: require('../../../images/Right_hand.png'),
    greaves: require('../../../images/Greaves.png'),
    rating1: require('../../../images/rating1.png'),
    rating2: require('../../../images/rating2.png'),
    rating3: require('../../../images/rating3.png'),
    rating4: require('../../../images/rating4.png'),
    rating5: require('../../../images/rating5.png'),
    rating: require('../../../images/rating.png'),
};

export default icons;